/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * ActivitySearchSubscriptionsRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class ActivitySearchSubscriptionsRequest {
    @SerializedName("UserIds")
    private List<String> userIds = null;

    @SerializedName("ObjectTypes")
    private List<ActivityOwnerType> objectTypes = null;

    @SerializedName("ObjectIds")
    private List<String> objectIds = null;

    public ActivitySearchSubscriptionsRequest userIds(List<String> userIds) {
        this.userIds = userIds;
        return this;
    }

    public ActivitySearchSubscriptionsRequest addUserIdsItem(String userIdsItem) {
        if (this.userIds == null) {
            this.userIds = new ArrayList<String>();
        }
        this.userIds.add(userIdsItem);
        return this;
    }

    /**
     * Get userIds
     *
     * @return userIds
     **/
    @ApiModelProperty(value = "")
    public List<String> getUserIds() {
        return userIds;
    }

    public void setUserIds(List<String> userIds) {
        this.userIds = userIds;
    }

    public ActivitySearchSubscriptionsRequest objectTypes(List<ActivityOwnerType> objectTypes) {
        this.objectTypes = objectTypes;
        return this;
    }

    public ActivitySearchSubscriptionsRequest addObjectTypesItem(ActivityOwnerType objectTypesItem) {
        if (this.objectTypes == null) {
            this.objectTypes = new ArrayList<ActivityOwnerType>();
        }
        this.objectTypes.add(objectTypesItem);
        return this;
    }

    /**
     * Get objectTypes
     *
     * @return objectTypes
     **/
    @ApiModelProperty(value = "")
    public List<ActivityOwnerType> getObjectTypes() {
        return objectTypes;
    }

    public void setObjectTypes(List<ActivityOwnerType> objectTypes) {
        this.objectTypes = objectTypes;
    }

    public ActivitySearchSubscriptionsRequest objectIds(List<String> objectIds) {
        this.objectIds = objectIds;
        return this;
    }

    public ActivitySearchSubscriptionsRequest addObjectIdsItem(String objectIdsItem) {
        if (this.objectIds == null) {
            this.objectIds = new ArrayList<String>();
        }
        this.objectIds.add(objectIdsItem);
        return this;
    }

    /**
     * Get objectIds
     *
     * @return objectIds
     **/
    @ApiModelProperty(value = "")
    public List<String> getObjectIds() {
        return objectIds;
    }

    public void setObjectIds(List<String> objectIds) {
        this.objectIds = objectIds;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ActivitySearchSubscriptionsRequest activitySearchSubscriptionsRequest = (ActivitySearchSubscriptionsRequest) o;
        return Objects.equals(this.userIds, activitySearchSubscriptionsRequest.userIds) &&
                Objects.equals(this.objectTypes, activitySearchSubscriptionsRequest.objectTypes) &&
                Objects.equals(this.objectIds, activitySearchSubscriptionsRequest.objectIds);
    }

    @Override
    public int hashCode() {
        return Objects.hash(userIds, objectTypes, objectIds);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class ActivitySearchSubscriptionsRequest {\n");

        sb.append("    userIds: ").append(toIndentedString(userIds)).append("\n");
        sb.append("    objectTypes: ").append(toIndentedString(objectTypes)).append("\n");
        sb.append("    objectIds: ").append(toIndentedString(objectIds)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

