/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * EncryptionAdminCreateKeyRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class EncryptionAdminCreateKeyRequest {
    @SerializedName("KeyID")
    private String keyID = null;

    @SerializedName("Label")
    private String label = null;

    public EncryptionAdminCreateKeyRequest keyID(String keyID) {
        this.keyID = keyID;
        return this;
    }

    /**
     * Get keyID
     *
     * @return keyID
     **/
    @ApiModelProperty(value = "")
    public String getKeyID() {
        return keyID;
    }

    public void setKeyID(String keyID) {
        this.keyID = keyID;
    }

    public EncryptionAdminCreateKeyRequest label(String label) {
        this.label = label;
        return this;
    }

    /**
     * Get label
     *
     * @return label
     **/
    @ApiModelProperty(value = "")
    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EncryptionAdminCreateKeyRequest encryptionAdminCreateKeyRequest = (EncryptionAdminCreateKeyRequest) o;
        return Objects.equals(this.keyID, encryptionAdminCreateKeyRequest.keyID) &&
                Objects.equals(this.label, encryptionAdminCreateKeyRequest.label);
    }

    @Override
    public int hashCode() {
        return Objects.hash(keyID, label);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class EncryptionAdminCreateKeyRequest {\n");

        sb.append("    keyID: ").append(toIndentedString(keyID)).append("\n");
        sb.append("    label: ").append(toIndentedString(label)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

