/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * IdmACL
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class IdmACL {
  @SerializedName("ID")
  private String ID = null;

  @SerializedName("Action")
  private IdmACLAction action = null;

  @SerializedName("RoleID")
  private String roleID = null;

  @SerializedName("WorkspaceID")
  private String workspaceID = null;

  @SerializedName("NodeID")
  private String nodeID = null;

  public IdmACL ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public IdmACL action(IdmACLAction action) {
    this.action = action;
    return this;
  }

   /**
   * Get action
   * @return action
  **/
  @ApiModelProperty(value = "")
  public IdmACLAction getAction() {
    return action;
  }

  public void setAction(IdmACLAction action) {
    this.action = action;
  }

  public IdmACL roleID(String roleID) {
    this.roleID = roleID;
    return this;
  }

   /**
   * Get roleID
   * @return roleID
  **/
  @ApiModelProperty(value = "")
  public String getRoleID() {
    return roleID;
  }

  public void setRoleID(String roleID) {
    this.roleID = roleID;
  }

  public IdmACL workspaceID(String workspaceID) {
    this.workspaceID = workspaceID;
    return this;
  }

   /**
   * Get workspaceID
   * @return workspaceID
  **/
  @ApiModelProperty(value = "")
  public String getWorkspaceID() {
    return workspaceID;
  }

  public void setWorkspaceID(String workspaceID) {
    this.workspaceID = workspaceID;
  }

  public IdmACL nodeID(String nodeID) {
    this.nodeID = nodeID;
    return this;
  }

   /**
   * Get nodeID
   * @return nodeID
  **/
  @ApiModelProperty(value = "")
  public String getNodeID() {
    return nodeID;
  }

  public void setNodeID(String nodeID) {
    this.nodeID = nodeID;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdmACL idmACL = (IdmACL) o;
    return Objects.equals(this.ID, idmACL.ID) &&
        Objects.equals(this.action, idmACL.action) &&
        Objects.equals(this.roleID, idmACL.roleID) &&
        Objects.equals(this.workspaceID, idmACL.workspaceID) &&
        Objects.equals(this.nodeID, idmACL.nodeID);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ID, action, roleID, workspaceID, nodeID);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdmACL {\n");
    
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    roleID: ").append(toIndentedString(roleID)).append("\n");
    sb.append("    workspaceID: ").append(toIndentedString(workspaceID)).append("\n");
    sb.append("    nodeID: ").append(toIndentedString(nodeID)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

