/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets idmNodeType
 */
@JsonAdapter(IdmNodeType.Adapter.class)
public enum IdmNodeType {
  
  UNKNOWN("UNKNOWN"),
  
  USER("USER"),
  
  GROUP("GROUP");

  private String value;

  IdmNodeType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IdmNodeType fromValue(String text) {
    for (IdmNodeType b : IdmNodeType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<IdmNodeType> {
    @Override
    public void write(final JsonWriter jsonWriter, final IdmNodeType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IdmNodeType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IdmNodeType.fromValue(String.valueOf(value));
    }
  }
}

