/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets idmWorkspaceScope
 */
@JsonAdapter(IdmWorkspaceScope.Adapter.class)
public enum IdmWorkspaceScope {
  
  ANY("ANY"),
  
  ADMIN("ADMIN"),
  
  ROOM("ROOM"),
  
  LINK("LINK");

  private String value;

  IdmWorkspaceScope(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static IdmWorkspaceScope fromValue(String text) {
    for (IdmWorkspaceScope b : IdmWorkspaceScope.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<IdmWorkspaceScope> {
    @Override
    public void write(final JsonWriter jsonWriter, final IdmWorkspaceScope enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public IdmWorkspaceScope read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return IdmWorkspaceScope.fromValue(String.valueOf(value));
    }
  }
}

