/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * JobsDeleteTasksResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class JobsDeleteTasksResponse {
    @SerializedName("Deleted")
    private List<String> deleted = null;

    public JobsDeleteTasksResponse deleted(List<String> deleted) {
        this.deleted = deleted;
        return this;
    }

    public JobsDeleteTasksResponse addDeletedItem(String deletedItem) {
        if (this.deleted == null) {
            this.deleted = new ArrayList<String>();
        }
        this.deleted.add(deletedItem);
        return this;
    }

    /**
     * Get deleted
     *
     * @return deleted
     **/
    @ApiModelProperty(value = "")
    public List<String> getDeleted() {
        return deleted;
    }

    public void setDeleted(List<String> deleted) {
        this.deleted = deleted;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JobsDeleteTasksResponse jobsDeleteTasksResponse = (JobsDeleteTasksResponse) o;
        return Objects.equals(this.deleted, jobsDeleteTasksResponse.deleted);
    }

    @Override
    public int hashCode() {
        return Objects.hash(deleted);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class JobsDeleteTasksResponse {\n");

        sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

