/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * JobsUsersSelector
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class JobsUsersSelector {
  @SerializedName("All")
  private Boolean all = null;

  @SerializedName("Users")
  private List<IdmUser> users = null;

  @SerializedName("Query")
  private ServiceQuery query = null;

  @SerializedName("Collect")
  private Boolean collect = null;

  public JobsUsersSelector all(Boolean all) {
    this.all = all;
    return this;
  }

   /**
   * Get all
   * @return all
  **/
  @ApiModelProperty(value = "")
  public Boolean isAll() {
    return all;
  }

  public void setAll(Boolean all) {
    this.all = all;
  }

  public JobsUsersSelector users(List<IdmUser> users) {
    this.users = users;
    return this;
  }

  public JobsUsersSelector addUsersItem(IdmUser usersItem) {
    if (this.users == null) {
      this.users = new ArrayList<IdmUser>();
    }
    this.users.add(usersItem);
    return this;
  }

   /**
   * Get users
   * @return users
  **/
  @ApiModelProperty(value = "")
  public List<IdmUser> getUsers() {
    return users;
  }

  public void setUsers(List<IdmUser> users) {
    this.users = users;
  }

  public JobsUsersSelector query(ServiceQuery query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(value = "")
  public ServiceQuery getQuery() {
    return query;
  }

  public void setQuery(ServiceQuery query) {
    this.query = query;
  }

  public JobsUsersSelector collect(Boolean collect) {
    this.collect = collect;
    return this;
  }

   /**
   * Get collect
   * @return collect
  **/
  @ApiModelProperty(value = "")
  public Boolean isCollect() {
    return collect;
  }

  public void setCollect(Boolean collect) {
    this.collect = collect;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobsUsersSelector jobsUsersSelector = (JobsUsersSelector) o;
    return Objects.equals(this.all, jobsUsersSelector.all) &&
        Objects.equals(this.users, jobsUsersSelector.users) &&
        Objects.equals(this.query, jobsUsersSelector.query) &&
        Objects.equals(this.collect, jobsUsersSelector.collect);
  }

  @Override
  public int hashCode() {
    return Objects.hash(all, users, query, collect);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobsUsersSelector {\n");
    
    sb.append("    all: ").append(toIndentedString(all)).append("\n");
    sb.append("    users: ").append(toIndentedString(users)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("    collect: ").append(toIndentedString(collect)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

