/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LogMessage is the format used to transmit log messages to clients via the REST API.
 */
@ApiModel(description = "LogMessage is the format used to transmit log messages to clients via the REST API.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class LogLogMessage {
  @SerializedName("Ts")
  private Integer ts = null;

  @SerializedName("Level")
  private String level = null;

  @SerializedName("Logger")
  private String logger = null;

  @SerializedName("Msg")
  private String msg = null;

  @SerializedName("MsgId")
  private String msgId = null;

  @SerializedName("UserName")
  private String userName = null;

  @SerializedName("UserUuid")
  private String userUuid = null;

  @SerializedName("GroupPath")
  private String groupPath = null;

  @SerializedName("Profile")
  private String profile = null;

  @SerializedName("RoleUuids")
  private List<String> roleUuids = null;

  @SerializedName("RemoteAddress")
  private String remoteAddress = null;

  @SerializedName("UserAgent")
  private String userAgent = null;

  @SerializedName("HttpProtocol")
  private String httpProtocol = null;

  @SerializedName("NodeUuid")
  private String nodeUuid = null;

  @SerializedName("NodePath")
  private String nodePath = null;

  @SerializedName("WsUuid")
  private String wsUuid = null;

  @SerializedName("WsScope")
  private String wsScope = null;

  @SerializedName("SpanUuid")
  private String spanUuid = null;

  @SerializedName("SpanParentUuid")
  private String spanParentUuid = null;

  @SerializedName("SpanRootUuid")
  private String spanRootUuid = null;

  public LogLogMessage ts(Integer ts) {
    this.ts = ts;
    return this;
  }

   /**
   * Get ts
   * @return ts
  **/
  @ApiModelProperty(value = "")
  public Integer getTs() {
    return ts;
  }

  public void setTs(Integer ts) {
    this.ts = ts;
  }

  public LogLogMessage level(String level) {
    this.level = level;
    return this;
  }

   /**
   * Get level
   * @return level
  **/
  @ApiModelProperty(value = "")
  public String getLevel() {
    return level;
  }

  public void setLevel(String level) {
    this.level = level;
  }

  public LogLogMessage logger(String logger) {
    this.logger = logger;
    return this;
  }

   /**
   * Get logger
   * @return logger
  **/
  @ApiModelProperty(value = "")
  public String getLogger() {
    return logger;
  }

  public void setLogger(String logger) {
    this.logger = logger;
  }

  public LogLogMessage msg(String msg) {
    this.msg = msg;
    return this;
  }

   /**
   * Get msg
   * @return msg
  **/
  @ApiModelProperty(value = "")
  public String getMsg() {
    return msg;
  }

  public void setMsg(String msg) {
    this.msg = msg;
  }

  public LogLogMessage msgId(String msgId) {
    this.msgId = msgId;
    return this;
  }

   /**
   * Get msgId
   * @return msgId
  **/
  @ApiModelProperty(value = "")
  public String getMsgId() {
    return msgId;
  }

  public void setMsgId(String msgId) {
    this.msgId = msgId;
  }

  public LogLogMessage userName(String userName) {
    this.userName = userName;
    return this;
  }

   /**
   * Get userName
   * @return userName
  **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public LogLogMessage userUuid(String userUuid) {
    this.userUuid = userUuid;
    return this;
  }

   /**
   * Get userUuid
   * @return userUuid
  **/
  @ApiModelProperty(value = "")
  public String getUserUuid() {
    return userUuid;
  }

  public void setUserUuid(String userUuid) {
    this.userUuid = userUuid;
  }

  public LogLogMessage groupPath(String groupPath) {
    this.groupPath = groupPath;
    return this;
  }

   /**
   * Get groupPath
   * @return groupPath
  **/
  @ApiModelProperty(value = "")
  public String getGroupPath() {
    return groupPath;
  }

  public void setGroupPath(String groupPath) {
    this.groupPath = groupPath;
  }

  public LogLogMessage profile(String profile) {
    this.profile = profile;
    return this;
  }

   /**
   * Get profile
   * @return profile
  **/
  @ApiModelProperty(value = "")
  public String getProfile() {
    return profile;
  }

  public void setProfile(String profile) {
    this.profile = profile;
  }

  public LogLogMessage roleUuids(List<String> roleUuids) {
    this.roleUuids = roleUuids;
    return this;
  }

  public LogLogMessage addRoleUuidsItem(String roleUuidsItem) {
    if (this.roleUuids == null) {
      this.roleUuids = new ArrayList<String>();
    }
    this.roleUuids.add(roleUuidsItem);
    return this;
  }

   /**
   * Get roleUuids
   * @return roleUuids
  **/
  @ApiModelProperty(value = "")
  public List<String> getRoleUuids() {
    return roleUuids;
  }

  public void setRoleUuids(List<String> roleUuids) {
    this.roleUuids = roleUuids;
  }

  public LogLogMessage remoteAddress(String remoteAddress) {
    this.remoteAddress = remoteAddress;
    return this;
  }

   /**
   * Get remoteAddress
   * @return remoteAddress
  **/
  @ApiModelProperty(value = "")
  public String getRemoteAddress() {
    return remoteAddress;
  }

  public void setRemoteAddress(String remoteAddress) {
    this.remoteAddress = remoteAddress;
  }

  public LogLogMessage userAgent(String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

   /**
   * Get userAgent
   * @return userAgent
  **/
  @ApiModelProperty(value = "")
  public String getUserAgent() {
    return userAgent;
  }

  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }

  public LogLogMessage httpProtocol(String httpProtocol) {
    this.httpProtocol = httpProtocol;
    return this;
  }

   /**
   * Get httpProtocol
   * @return httpProtocol
  **/
  @ApiModelProperty(value = "")
  public String getHttpProtocol() {
    return httpProtocol;
  }

  public void setHttpProtocol(String httpProtocol) {
    this.httpProtocol = httpProtocol;
  }

  public LogLogMessage nodeUuid(String nodeUuid) {
    this.nodeUuid = nodeUuid;
    return this;
  }

   /**
   * Get nodeUuid
   * @return nodeUuid
  **/
  @ApiModelProperty(value = "")
  public String getNodeUuid() {
    return nodeUuid;
  }

  public void setNodeUuid(String nodeUuid) {
    this.nodeUuid = nodeUuid;
  }

  public LogLogMessage nodePath(String nodePath) {
    this.nodePath = nodePath;
    return this;
  }

   /**
   * Get nodePath
   * @return nodePath
  **/
  @ApiModelProperty(value = "")
  public String getNodePath() {
    return nodePath;
  }

  public void setNodePath(String nodePath) {
    this.nodePath = nodePath;
  }

  public LogLogMessage wsUuid(String wsUuid) {
    this.wsUuid = wsUuid;
    return this;
  }

   /**
   * Get wsUuid
   * @return wsUuid
  **/
  @ApiModelProperty(value = "")
  public String getWsUuid() {
    return wsUuid;
  }

  public void setWsUuid(String wsUuid) {
    this.wsUuid = wsUuid;
  }

  public LogLogMessage wsScope(String wsScope) {
    this.wsScope = wsScope;
    return this;
  }

   /**
   * Get wsScope
   * @return wsScope
  **/
  @ApiModelProperty(value = "")
  public String getWsScope() {
    return wsScope;
  }

  public void setWsScope(String wsScope) {
    this.wsScope = wsScope;
  }

  public LogLogMessage spanUuid(String spanUuid) {
    this.spanUuid = spanUuid;
    return this;
  }

   /**
   * Get spanUuid
   * @return spanUuid
  **/
  @ApiModelProperty(value = "")
  public String getSpanUuid() {
    return spanUuid;
  }

  public void setSpanUuid(String spanUuid) {
    this.spanUuid = spanUuid;
  }

  public LogLogMessage spanParentUuid(String spanParentUuid) {
    this.spanParentUuid = spanParentUuid;
    return this;
  }

   /**
   * Get spanParentUuid
   * @return spanParentUuid
  **/
  @ApiModelProperty(value = "")
  public String getSpanParentUuid() {
    return spanParentUuid;
  }

  public void setSpanParentUuid(String spanParentUuid) {
    this.spanParentUuid = spanParentUuid;
  }

  public LogLogMessage spanRootUuid(String spanRootUuid) {
    this.spanRootUuid = spanRootUuid;
    return this;
  }

   /**
   * Get spanRootUuid
   * @return spanRootUuid
  **/
  @ApiModelProperty(value = "")
  public String getSpanRootUuid() {
    return spanRootUuid;
  }

  public void setSpanRootUuid(String spanRootUuid) {
    this.spanRootUuid = spanRootUuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LogLogMessage logLogMessage = (LogLogMessage) o;
    return Objects.equals(this.ts, logLogMessage.ts) &&
        Objects.equals(this.level, logLogMessage.level) &&
        Objects.equals(this.logger, logLogMessage.logger) &&
        Objects.equals(this.msg, logLogMessage.msg) &&
        Objects.equals(this.msgId, logLogMessage.msgId) &&
        Objects.equals(this.userName, logLogMessage.userName) &&
        Objects.equals(this.userUuid, logLogMessage.userUuid) &&
        Objects.equals(this.groupPath, logLogMessage.groupPath) &&
        Objects.equals(this.profile, logLogMessage.profile) &&
        Objects.equals(this.roleUuids, logLogMessage.roleUuids) &&
        Objects.equals(this.remoteAddress, logLogMessage.remoteAddress) &&
        Objects.equals(this.userAgent, logLogMessage.userAgent) &&
        Objects.equals(this.httpProtocol, logLogMessage.httpProtocol) &&
        Objects.equals(this.nodeUuid, logLogMessage.nodeUuid) &&
        Objects.equals(this.nodePath, logLogMessage.nodePath) &&
        Objects.equals(this.wsUuid, logLogMessage.wsUuid) &&
        Objects.equals(this.wsScope, logLogMessage.wsScope) &&
        Objects.equals(this.spanUuid, logLogMessage.spanUuid) &&
        Objects.equals(this.spanParentUuid, logLogMessage.spanParentUuid) &&
        Objects.equals(this.spanRootUuid, logLogMessage.spanRootUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ts, level, logger, msg, msgId, userName, userUuid, groupPath, profile, roleUuids, remoteAddress, userAgent, httpProtocol, nodeUuid, nodePath, wsUuid, wsScope, spanUuid, spanParentUuid, spanRootUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LogLogMessage {\n");
    
    sb.append("    ts: ").append(toIndentedString(ts)).append("\n");
    sb.append("    level: ").append(toIndentedString(level)).append("\n");
    sb.append("    logger: ").append(toIndentedString(logger)).append("\n");
    sb.append("    msg: ").append(toIndentedString(msg)).append("\n");
    sb.append("    msgId: ").append(toIndentedString(msgId)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("    groupPath: ").append(toIndentedString(groupPath)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    roleUuids: ").append(toIndentedString(roleUuids)).append("\n");
    sb.append("    remoteAddress: ").append(toIndentedString(remoteAddress)).append("\n");
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    httpProtocol: ").append(toIndentedString(httpProtocol)).append("\n");
    sb.append("    nodeUuid: ").append(toIndentedString(nodeUuid)).append("\n");
    sb.append("    nodePath: ").append(toIndentedString(nodePath)).append("\n");
    sb.append("    wsUuid: ").append(toIndentedString(wsUuid)).append("\n");
    sb.append("    wsScope: ").append(toIndentedString(wsScope)).append("\n");
    sb.append("    spanUuid: ").append(toIndentedString(spanUuid)).append("\n");
    sb.append("    spanParentUuid: ").append(toIndentedString(spanParentUuid)).append("\n");
    sb.append("    spanRootUuid: ").append(toIndentedString(spanRootUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

