/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RestServiceCollection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class RestServiceCollection {
    @SerializedName("Services")
    private List<CtlService> services = null;

    @SerializedName("Total")
    private Integer total = null;

    public RestServiceCollection services(List<CtlService> services) {
        this.services = services;
        return this;
    }

    public RestServiceCollection addServicesItem(CtlService servicesItem) {
        if (this.services == null) {
            this.services = new ArrayList<CtlService>();
        }
        this.services.add(servicesItem);
        return this;
    }

    /**
     * Get services
     *
     * @return services
     **/
    @ApiModelProperty(value = "")
    public List<CtlService> getServices() {
        return services;
    }

    public void setServices(List<CtlService> services) {
        this.services = services;
    }

    public RestServiceCollection total(Integer total) {
        this.total = total;
        return this;
    }

    /**
     * Get total
     *
     * @return total
     **/
    @ApiModelProperty(value = "")
    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RestServiceCollection restServiceCollection = (RestServiceCollection) o;
        return Objects.equals(this.services, restServiceCollection.services) &&
                Objects.equals(this.total, restServiceCollection.total);
    }

    @Override
    public int hashCode() {
        return Objects.hash(services, total);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RestServiceCollection {\n");

        sb.append("    services: ").append(toIndentedString(services)).append("\n");
        sb.append("    total: ").append(toIndentedString(total)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

