/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RestUserJobResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class RestUserJobResponse {
  @SerializedName("JobUuid")
  private String jobUuid = null;

  public RestUserJobResponse jobUuid(String jobUuid) {
    this.jobUuid = jobUuid;
    return this;
  }

   /**
   * Get jobUuid
   * @return jobUuid
  **/
  @ApiModelProperty(value = "")
  public String getJobUuid() {
    return jobUuid;
  }

  public void setJobUuid(String jobUuid) {
    this.jobUuid = jobUuid;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestUserJobResponse restUserJobResponse = (RestUserJobResponse) o;
    return Objects.equals(this.jobUuid, restUserJobResponse.jobUuid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobUuid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestUserJobResponse {\n");
    
    sb.append("    jobUuid: ").append(toIndentedString(jobUuid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

