/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RestListSharedResourcesRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class RestListSharedResourcesRequest {
    @SerializedName("ShareType")
    private ListSharedResourcesRequestListShareType shareType = null;

    @SerializedName("Subject")
    private String subject = null;

    @SerializedName("OwnedBySubject")
    private Boolean ownedBySubject = null;

    @SerializedName("Offset")
    private Integer offset = null;

    @SerializedName("Limit")
    private Integer limit = null;

    public RestListSharedResourcesRequest shareType(ListSharedResourcesRequestListShareType shareType) {
        this.shareType = shareType;
        return this;
    }

    /**
     * Get shareType
     *
     * @return shareType
     **/
    @ApiModelProperty(value = "")
    public ListSharedResourcesRequestListShareType getShareType() {
        return shareType;
    }

    public void setShareType(ListSharedResourcesRequestListShareType shareType) {
        this.shareType = shareType;
    }

    public RestListSharedResourcesRequest subject(String subject) {
        this.subject = subject;
        return this;
    }

    /**
     * Get subject
     *
     * @return subject
     **/
    @ApiModelProperty(value = "")
    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public RestListSharedResourcesRequest ownedBySubject(Boolean ownedBySubject) {
        this.ownedBySubject = ownedBySubject;
        return this;
    }

    /**
     * Get ownedBySubject
     *
     * @return ownedBySubject
     **/
    @ApiModelProperty(value = "")
    public Boolean isOwnedBySubject() {
        return ownedBySubject;
    }

    public void setOwnedBySubject(Boolean ownedBySubject) {
        this.ownedBySubject = ownedBySubject;
    }

    public RestListSharedResourcesRequest offset(Integer offset) {
        this.offset = offset;
        return this;
    }

    /**
     * Get offset
     *
     * @return offset
     **/
    @ApiModelProperty(value = "")
    public Integer getOffset() {
        return offset;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public RestListSharedResourcesRequest limit(Integer limit) {
        this.limit = limit;
        return this;
    }

    /**
     * Get limit
     *
     * @return limit
     **/
    @ApiModelProperty(value = "")
    public Integer getLimit() {
        return limit;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RestListSharedResourcesRequest restListSharedResourcesRequest = (RestListSharedResourcesRequest) o;
        return Objects.equals(this.shareType, restListSharedResourcesRequest.shareType) &&
                Objects.equals(this.subject, restListSharedResourcesRequest.subject) &&
                Objects.equals(this.ownedBySubject, restListSharedResourcesRequest.ownedBySubject) &&
                Objects.equals(this.offset, restListSharedResourcesRequest.offset) &&
                Objects.equals(this.limit, restListSharedResourcesRequest.limit);
    }

    @Override
    public int hashCode() {
        return Objects.hash(shareType, subject, ownedBySubject, offset, limit);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RestListSharedResourcesRequest {\n");

        sb.append("    shareType: ").append(toIndentedString(shareType)).append("\n");
        sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
        sb.append("    ownedBySubject: ").append(toIndentedString(ownedBySubject)).append("\n");
        sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
        sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

