/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RestSearchACLRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class RestSearchACLRequest {
  @SerializedName("Queries")
  private List<IdmACLSingleQuery> queries = null;

  @SerializedName("Offset")
  private String offset = null;

  @SerializedName("Limit")
  private String limit = null;

  @SerializedName("GroupBy")
  private Integer groupBy = null;

  @SerializedName("CountOnly")
  private Boolean countOnly = null;

  @SerializedName("Operation")
  private ServiceOperationType operation = null;

  public RestSearchACLRequest queries(List<IdmACLSingleQuery> queries) {
    this.queries = queries;
    return this;
  }

  public RestSearchACLRequest addQueriesItem(IdmACLSingleQuery queriesItem) {
    if (this.queries == null) {
      this.queries = new ArrayList<IdmACLSingleQuery>();
    }
    this.queries.add(queriesItem);
    return this;
  }

   /**
   * Get queries
   * @return queries
  **/
  @ApiModelProperty(value = "")
  public List<IdmACLSingleQuery> getQueries() {
    return queries;
  }

  public void setQueries(List<IdmACLSingleQuery> queries) {
    this.queries = queries;
  }

  public RestSearchACLRequest offset(String offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  @ApiModelProperty(value = "")
  public String getOffset() {
    return offset;
  }

  public void setOffset(String offset) {
    this.offset = offset;
  }

  public RestSearchACLRequest limit(String limit) {
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @ApiModelProperty(value = "")
  public String getLimit() {
    return limit;
  }

  public void setLimit(String limit) {
    this.limit = limit;
  }

  public RestSearchACLRequest groupBy(Integer groupBy) {
    this.groupBy = groupBy;
    return this;
  }

   /**
   * Get groupBy
   * @return groupBy
  **/
  @ApiModelProperty(value = "")
  public Integer getGroupBy() {
    return groupBy;
  }

  public void setGroupBy(Integer groupBy) {
    this.groupBy = groupBy;
  }

  public RestSearchACLRequest countOnly(Boolean countOnly) {
    this.countOnly = countOnly;
    return this;
  }

   /**
   * Get countOnly
   * @return countOnly
  **/
  @ApiModelProperty(value = "")
  public Boolean isCountOnly() {
    return countOnly;
  }

  public void setCountOnly(Boolean countOnly) {
    this.countOnly = countOnly;
  }

  public RestSearchACLRequest operation(ServiceOperationType operation) {
    this.operation = operation;
    return this;
  }

   /**
   * Get operation
   * @return operation
  **/
  @ApiModelProperty(value = "")
  public ServiceOperationType getOperation() {
    return operation;
  }

  public void setOperation(ServiceOperationType operation) {
    this.operation = operation;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSearchACLRequest restSearchACLRequest = (RestSearchACLRequest) o;
    return Objects.equals(this.queries, restSearchACLRequest.queries) &&
        Objects.equals(this.offset, restSearchACLRequest.offset) &&
        Objects.equals(this.limit, restSearchACLRequest.limit) &&
        Objects.equals(this.groupBy, restSearchACLRequest.groupBy) &&
        Objects.equals(this.countOnly, restSearchACLRequest.countOnly) &&
        Objects.equals(this.operation, restSearchACLRequest.operation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queries, offset, limit, groupBy, countOnly, operation);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSearchACLRequest {\n");
    
    sb.append("    queries: ").append(toIndentedString(queries)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    groupBy: ").append(toIndentedString(groupBy)).append("\n");
    sb.append("    countOnly: ").append(toIndentedString(countOnly)).append("\n");
    sb.append("    operation: ").append(toIndentedString(operation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

