/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * RestShareLink
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class RestShareLink {
  @SerializedName("Uuid")
  private String uuid = null;

  @SerializedName("LinkHash")
  private String linkHash = null;

  @SerializedName("LinkUrl")
  private String linkUrl = null;

  @SerializedName("Label")
  private String label = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("UserUuid")
  private String userUuid = null;

  @SerializedName("UserLogin")
  private String userLogin = null;

  @SerializedName("PasswordRequired")
  private Boolean passwordRequired = null;

  @SerializedName("AccessStart")
  private String accessStart = null;

  @SerializedName("AccessEnd")
  private String accessEnd = null;

  @SerializedName("MaxDownloads")
  private String maxDownloads = null;

  @SerializedName("CurrentDownloads")
  private String currentDownloads = null;

  @SerializedName("ViewTemplateName")
  private String viewTemplateName = null;

  @SerializedName("TargetUsers")
  private Map<String, RestShareLinkTargetUser> targetUsers = null;

  @SerializedName("RestrictToTargetUsers")
  private Boolean restrictToTargetUsers = null;

  @SerializedName("RootNodes")
  private List<TreeNode> rootNodes = null;

  @SerializedName("Permissions")
  private List<RestShareLinkAccessType> permissions = null;

  @SerializedName("Policies")
  private List<ServiceResourcePolicy> policies = null;

  @SerializedName("PoliciesContextEditable")
  private Boolean policiesContextEditable = null;

  public RestShareLink uuid(String uuid) {
    this.uuid = uuid;
    return this;
  }

   /**
   * Get uuid
   * @return uuid
  **/
  @ApiModelProperty(value = "")
  public String getUuid() {
    return uuid;
  }

  public void setUuid(String uuid) {
    this.uuid = uuid;
  }

  public RestShareLink linkHash(String linkHash) {
    this.linkHash = linkHash;
    return this;
  }

   /**
   * Get linkHash
   * @return linkHash
  **/
  @ApiModelProperty(value = "")
  public String getLinkHash() {
    return linkHash;
  }

  public void setLinkHash(String linkHash) {
    this.linkHash = linkHash;
  }

  public RestShareLink linkUrl(String linkUrl) {
    this.linkUrl = linkUrl;
    return this;
  }

   /**
   * Get linkUrl
   * @return linkUrl
  **/
  @ApiModelProperty(value = "")
  public String getLinkUrl() {
    return linkUrl;
  }

  public void setLinkUrl(String linkUrl) {
    this.linkUrl = linkUrl;
  }

  public RestShareLink label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public RestShareLink description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public RestShareLink userUuid(String userUuid) {
    this.userUuid = userUuid;
    return this;
  }

   /**
   * Get userUuid
   * @return userUuid
  **/
  @ApiModelProperty(value = "")
  public String getUserUuid() {
    return userUuid;
  }

  public void setUserUuid(String userUuid) {
    this.userUuid = userUuid;
  }

  public RestShareLink userLogin(String userLogin) {
    this.userLogin = userLogin;
    return this;
  }

   /**
   * Get userLogin
   * @return userLogin
  **/
  @ApiModelProperty(value = "")
  public String getUserLogin() {
    return userLogin;
  }

  public void setUserLogin(String userLogin) {
    this.userLogin = userLogin;
  }

  public RestShareLink passwordRequired(Boolean passwordRequired) {
    this.passwordRequired = passwordRequired;
    return this;
  }

   /**
   * Get passwordRequired
   * @return passwordRequired
  **/
  @ApiModelProperty(value = "")
  public Boolean isPasswordRequired() {
    return passwordRequired;
  }

  public void setPasswordRequired(Boolean passwordRequired) {
    this.passwordRequired = passwordRequired;
  }

  public RestShareLink accessStart(String accessStart) {
    this.accessStart = accessStart;
    return this;
  }

   /**
   * Get accessStart
   * @return accessStart
  **/
  @ApiModelProperty(value = "")
  public String getAccessStart() {
    return accessStart;
  }

  public void setAccessStart(String accessStart) {
    this.accessStart = accessStart;
  }

  public RestShareLink accessEnd(String accessEnd) {
    this.accessEnd = accessEnd;
    return this;
  }

   /**
   * Get accessEnd
   * @return accessEnd
  **/
  @ApiModelProperty(value = "")
  public String getAccessEnd() {
    return accessEnd;
  }

  public void setAccessEnd(String accessEnd) {
    this.accessEnd = accessEnd;
  }

  public RestShareLink maxDownloads(String maxDownloads) {
    this.maxDownloads = maxDownloads;
    return this;
  }

   /**
   * Get maxDownloads
   * @return maxDownloads
  **/
  @ApiModelProperty(value = "")
  public String getMaxDownloads() {
    return maxDownloads;
  }

  public void setMaxDownloads(String maxDownloads) {
    this.maxDownloads = maxDownloads;
  }

  public RestShareLink currentDownloads(String currentDownloads) {
    this.currentDownloads = currentDownloads;
    return this;
  }

   /**
   * Get currentDownloads
   * @return currentDownloads
  **/
  @ApiModelProperty(value = "")
  public String getCurrentDownloads() {
    return currentDownloads;
  }

  public void setCurrentDownloads(String currentDownloads) {
    this.currentDownloads = currentDownloads;
  }

  public RestShareLink viewTemplateName(String viewTemplateName) {
    this.viewTemplateName = viewTemplateName;
    return this;
  }

   /**
   * Get viewTemplateName
   * @return viewTemplateName
  **/
  @ApiModelProperty(value = "")
  public String getViewTemplateName() {
    return viewTemplateName;
  }

  public void setViewTemplateName(String viewTemplateName) {
    this.viewTemplateName = viewTemplateName;
  }

  public RestShareLink targetUsers(Map<String, RestShareLinkTargetUser> targetUsers) {
    this.targetUsers = targetUsers;
    return this;
  }

  public RestShareLink putTargetUsersItem(String key, RestShareLinkTargetUser targetUsersItem) {
    if (this.targetUsers == null) {
      this.targetUsers = new HashMap<String, RestShareLinkTargetUser>();
    }
    this.targetUsers.put(key, targetUsersItem);
    return this;
  }

   /**
   * Get targetUsers
   * @return targetUsers
  **/
  @ApiModelProperty(value = "")
  public Map<String, RestShareLinkTargetUser> getTargetUsers() {
    return targetUsers;
  }

  public void setTargetUsers(Map<String, RestShareLinkTargetUser> targetUsers) {
    this.targetUsers = targetUsers;
  }

  public RestShareLink restrictToTargetUsers(Boolean restrictToTargetUsers) {
    this.restrictToTargetUsers = restrictToTargetUsers;
    return this;
  }

   /**
   * Get restrictToTargetUsers
   * @return restrictToTargetUsers
  **/
  @ApiModelProperty(value = "")
  public Boolean isRestrictToTargetUsers() {
    return restrictToTargetUsers;
  }

  public void setRestrictToTargetUsers(Boolean restrictToTargetUsers) {
    this.restrictToTargetUsers = restrictToTargetUsers;
  }

  public RestShareLink rootNodes(List<TreeNode> rootNodes) {
    this.rootNodes = rootNodes;
    return this;
  }

  public RestShareLink addRootNodesItem(TreeNode rootNodesItem) {
    if (this.rootNodes == null) {
      this.rootNodes = new ArrayList<TreeNode>();
    }
    this.rootNodes.add(rootNodesItem);
    return this;
  }

   /**
   * Get rootNodes
   * @return rootNodes
  **/
  @ApiModelProperty(value = "")
  public List<TreeNode> getRootNodes() {
    return rootNodes;
  }

  public void setRootNodes(List<TreeNode> rootNodes) {
    this.rootNodes = rootNodes;
  }

  public RestShareLink permissions(List<RestShareLinkAccessType> permissions) {
    this.permissions = permissions;
    return this;
  }

  public RestShareLink addPermissionsItem(RestShareLinkAccessType permissionsItem) {
    if (this.permissions == null) {
      this.permissions = new ArrayList<RestShareLinkAccessType>();
    }
    this.permissions.add(permissionsItem);
    return this;
  }

   /**
   * Get permissions
   * @return permissions
  **/
  @ApiModelProperty(value = "")
  public List<RestShareLinkAccessType> getPermissions() {
    return permissions;
  }

  public void setPermissions(List<RestShareLinkAccessType> permissions) {
    this.permissions = permissions;
  }

  public RestShareLink policies(List<ServiceResourcePolicy> policies) {
    this.policies = policies;
    return this;
  }

  public RestShareLink addPoliciesItem(ServiceResourcePolicy policiesItem) {
    if (this.policies == null) {
      this.policies = new ArrayList<ServiceResourcePolicy>();
    }
    this.policies.add(policiesItem);
    return this;
  }

   /**
   * Get policies
   * @return policies
  **/
  @ApiModelProperty(value = "")
  public List<ServiceResourcePolicy> getPolicies() {
    return policies;
  }

  public void setPolicies(List<ServiceResourcePolicy> policies) {
    this.policies = policies;
  }

  public RestShareLink policiesContextEditable(Boolean policiesContextEditable) {
    this.policiesContextEditable = policiesContextEditable;
    return this;
  }

   /**
   * Get policiesContextEditable
   * @return policiesContextEditable
  **/
  @ApiModelProperty(value = "")
  public Boolean isPoliciesContextEditable() {
    return policiesContextEditable;
  }

  public void setPoliciesContextEditable(Boolean policiesContextEditable) {
    this.policiesContextEditable = policiesContextEditable;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestShareLink restShareLink = (RestShareLink) o;
    return Objects.equals(this.uuid, restShareLink.uuid) &&
        Objects.equals(this.linkHash, restShareLink.linkHash) &&
        Objects.equals(this.linkUrl, restShareLink.linkUrl) &&
        Objects.equals(this.label, restShareLink.label) &&
        Objects.equals(this.description, restShareLink.description) &&
        Objects.equals(this.userUuid, restShareLink.userUuid) &&
        Objects.equals(this.userLogin, restShareLink.userLogin) &&
        Objects.equals(this.passwordRequired, restShareLink.passwordRequired) &&
        Objects.equals(this.accessStart, restShareLink.accessStart) &&
        Objects.equals(this.accessEnd, restShareLink.accessEnd) &&
        Objects.equals(this.maxDownloads, restShareLink.maxDownloads) &&
        Objects.equals(this.currentDownloads, restShareLink.currentDownloads) &&
        Objects.equals(this.viewTemplateName, restShareLink.viewTemplateName) &&
        Objects.equals(this.targetUsers, restShareLink.targetUsers) &&
        Objects.equals(this.restrictToTargetUsers, restShareLink.restrictToTargetUsers) &&
        Objects.equals(this.rootNodes, restShareLink.rootNodes) &&
        Objects.equals(this.permissions, restShareLink.permissions) &&
        Objects.equals(this.policies, restShareLink.policies) &&
        Objects.equals(this.policiesContextEditable, restShareLink.policiesContextEditable);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uuid, linkHash, linkUrl, label, description, userUuid, userLogin, passwordRequired, accessStart, accessEnd, maxDownloads, currentDownloads, viewTemplateName, targetUsers, restrictToTargetUsers, rootNodes, permissions, policies, policiesContextEditable);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestShareLink {\n");
    
    sb.append("    uuid: ").append(toIndentedString(uuid)).append("\n");
    sb.append("    linkHash: ").append(toIndentedString(linkHash)).append("\n");
    sb.append("    linkUrl: ").append(toIndentedString(linkUrl)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    userUuid: ").append(toIndentedString(userUuid)).append("\n");
    sb.append("    userLogin: ").append(toIndentedString(userLogin)).append("\n");
    sb.append("    passwordRequired: ").append(toIndentedString(passwordRequired)).append("\n");
    sb.append("    accessStart: ").append(toIndentedString(accessStart)).append("\n");
    sb.append("    accessEnd: ").append(toIndentedString(accessEnd)).append("\n");
    sb.append("    maxDownloads: ").append(toIndentedString(maxDownloads)).append("\n");
    sb.append("    currentDownloads: ").append(toIndentedString(currentDownloads)).append("\n");
    sb.append("    viewTemplateName: ").append(toIndentedString(viewTemplateName)).append("\n");
    sb.append("    targetUsers: ").append(toIndentedString(targetUsers)).append("\n");
    sb.append("    restrictToTargetUsers: ").append(toIndentedString(restrictToTargetUsers)).append("\n");
    sb.append("    rootNodes: ").append(toIndentedString(rootNodes)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("    policies: ").append(toIndentedString(policies)).append("\n");
    sb.append("    policiesContextEditable: ").append(toIndentedString(policiesContextEditable)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

