/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * TreeNodeChangeEvent
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class TreeNodeChangeEvent {
    @SerializedName("Type")
    private NodeChangeEventEventType type = null;

    @SerializedName("Source")
    private TreeNode source = null;

    @SerializedName("Target")
    private TreeNode target = null;

    public TreeNodeChangeEvent type(NodeChangeEventEventType type) {
        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     **/
    @ApiModelProperty(value = "")
    public NodeChangeEventEventType getType() {
        return type;
    }

    public void setType(NodeChangeEventEventType type) {
        this.type = type;
    }

    public TreeNodeChangeEvent source(TreeNode source) {
        this.source = source;
        return this;
    }

    /**
     * Get source
     *
     * @return source
     **/
    @ApiModelProperty(value = "")
    public TreeNode getSource() {
        return source;
    }

    public void setSource(TreeNode source) {
        this.source = source;
    }

    public TreeNodeChangeEvent target(TreeNode target) {
        this.target = target;
        return this;
    }

    /**
     * Get target
     *
     * @return target
     **/
    @ApiModelProperty(value = "")
    public TreeNode getTarget() {
        return target;
    }

    public void setTarget(TreeNode target) {
        this.target = target;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TreeNodeChangeEvent treeNodeChangeEvent = (TreeNodeChangeEvent) o;
        return Objects.equals(this.type, treeNodeChangeEvent.type) &&
                Objects.equals(this.source, treeNodeChangeEvent.source) &&
                Objects.equals(this.target, treeNodeChangeEvent.target);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, source, target);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class TreeNodeChangeEvent {\n");

        sb.append("    type: ").append(toIndentedString(type)).append("\n");
        sb.append("    source: ").append(toIndentedString(source)).append("\n");
        sb.append("    target: ").append(toIndentedString(target)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

