/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pydio.sdk.core.api.cells.model;

import com.google.gson.annotations.SerializedName;

import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * UpdatePackage
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-30T14:51:15.861Z")
public class UpdatePackage {
  @SerializedName("PackageName")
  private String packageName = null;

  @SerializedName("Version")
  private String version = null;

  @SerializedName("ReleaseDate")
  private Integer releaseDate = null;

  @SerializedName("Label")
  private String label = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("ChangeLog")
  private String changeLog = null;

  @SerializedName("License")
  private String license = null;

  @SerializedName("BinaryURL")
  private String binaryURL = null;

  @SerializedName("BinaryChecksum")
  private String binaryChecksum = null;

  @SerializedName("BinarySignature")
  private String binarySignature = null;

  @SerializedName("BinaryHashType")
  private String binaryHashType = null;

  @SerializedName("BinarySize")
  private String binarySize = null;

  @SerializedName("BinaryOS")
  private String binaryOS = null;

  @SerializedName("BinaryArch")
  private String binaryArch = null;

  @SerializedName("IsPatch")
  private Boolean isPatch = null;

  @SerializedName("PatchAlgorithm")
  private String patchAlgorithm = null;

  @SerializedName("ServiceName")
  private String serviceName = null;

  @SerializedName("Status")
  private PackagePackageStatus status = null;

  public UpdatePackage packageName(String packageName) {
    this.packageName = packageName;
    return this;
  }

   /**
   * Get packageName
   * @return packageName
  **/
  @ApiModelProperty(value = "")
  public String getPackageName() {
    return packageName;
  }

  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }

  public UpdatePackage version(String version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public String getVersion() {
    return version;
  }

  public void setVersion(String version) {
    this.version = version;
  }

  public UpdatePackage releaseDate(Integer releaseDate) {
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @ApiModelProperty(value = "")
  public Integer getReleaseDate() {
    return releaseDate;
  }

  public void setReleaseDate(Integer releaseDate) {
    this.releaseDate = releaseDate;
  }

  public UpdatePackage label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @ApiModelProperty(value = "")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public UpdatePackage description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public UpdatePackage changeLog(String changeLog) {
    this.changeLog = changeLog;
    return this;
  }

   /**
   * Get changeLog
   * @return changeLog
  **/
  @ApiModelProperty(value = "")
  public String getChangeLog() {
    return changeLog;
  }

  public void setChangeLog(String changeLog) {
    this.changeLog = changeLog;
  }

  public UpdatePackage license(String license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @ApiModelProperty(value = "")
  public String getLicense() {
    return license;
  }

  public void setLicense(String license) {
    this.license = license;
  }

  public UpdatePackage binaryURL(String binaryURL) {
    this.binaryURL = binaryURL;
    return this;
  }

   /**
   * Get binaryURL
   * @return binaryURL
  **/
  @ApiModelProperty(value = "")
  public String getBinaryURL() {
    return binaryURL;
  }

  public void setBinaryURL(String binaryURL) {
    this.binaryURL = binaryURL;
  }

  public UpdatePackage binaryChecksum(String binaryChecksum) {
    this.binaryChecksum = binaryChecksum;
    return this;
  }

   /**
   * Get binaryChecksum
   * @return binaryChecksum
  **/
  @ApiModelProperty(value = "")
  public String getBinaryChecksum() {
    return binaryChecksum;
  }

  public void setBinaryChecksum(String binaryChecksum) {
    this.binaryChecksum = binaryChecksum;
  }

  public UpdatePackage binarySignature(String binarySignature) {
    this.binarySignature = binarySignature;
    return this;
  }

   /**
   * Get binarySignature
   * @return binarySignature
  **/
  @ApiModelProperty(value = "")
  public String getBinarySignature() {
    return binarySignature;
  }

  public void setBinarySignature(String binarySignature) {
    this.binarySignature = binarySignature;
  }

  public UpdatePackage binaryHashType(String binaryHashType) {
    this.binaryHashType = binaryHashType;
    return this;
  }

   /**
   * Get binaryHashType
   * @return binaryHashType
  **/
  @ApiModelProperty(value = "")
  public String getBinaryHashType() {
    return binaryHashType;
  }

  public void setBinaryHashType(String binaryHashType) {
    this.binaryHashType = binaryHashType;
  }

  public UpdatePackage binarySize(String binarySize) {
    this.binarySize = binarySize;
    return this;
  }

   /**
   * Get binarySize
   * @return binarySize
  **/
  @ApiModelProperty(value = "")
  public String getBinarySize() {
    return binarySize;
  }

  public void setBinarySize(String binarySize) {
    this.binarySize = binarySize;
  }

  public UpdatePackage binaryOS(String binaryOS) {
    this.binaryOS = binaryOS;
    return this;
  }

   /**
   * Get binaryOS
   * @return binaryOS
  **/
  @ApiModelProperty(value = "")
  public String getBinaryOS() {
    return binaryOS;
  }

  public void setBinaryOS(String binaryOS) {
    this.binaryOS = binaryOS;
  }

  public UpdatePackage binaryArch(String binaryArch) {
    this.binaryArch = binaryArch;
    return this;
  }

   /**
   * Get binaryArch
   * @return binaryArch
  **/
  @ApiModelProperty(value = "")
  public String getBinaryArch() {
    return binaryArch;
  }

  public void setBinaryArch(String binaryArch) {
    this.binaryArch = binaryArch;
  }

  public UpdatePackage isPatch(Boolean isPatch) {
    this.isPatch = isPatch;
    return this;
  }

   /**
   * Get isPatch
   * @return isPatch
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsPatch() {
    return isPatch;
  }

  public void setIsPatch(Boolean isPatch) {
    this.isPatch = isPatch;
  }

  public UpdatePackage patchAlgorithm(String patchAlgorithm) {
    this.patchAlgorithm = patchAlgorithm;
    return this;
  }

   /**
   * Get patchAlgorithm
   * @return patchAlgorithm
  **/
  @ApiModelProperty(value = "")
  public String getPatchAlgorithm() {
    return patchAlgorithm;
  }

  public void setPatchAlgorithm(String patchAlgorithm) {
    this.patchAlgorithm = patchAlgorithm;
  }

  public UpdatePackage serviceName(String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Get serviceName
   * @return serviceName
  **/
  @ApiModelProperty(value = "")
  public String getServiceName() {
    return serviceName;
  }

  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }

  public UpdatePackage status(PackagePackageStatus status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @ApiModelProperty(value = "")
  public PackagePackageStatus getStatus() {
    return status;
  }

  public void setStatus(PackagePackageStatus status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePackage updatePackage = (UpdatePackage) o;
    return Objects.equals(this.packageName, updatePackage.packageName) &&
        Objects.equals(this.version, updatePackage.version) &&
        Objects.equals(this.releaseDate, updatePackage.releaseDate) &&
        Objects.equals(this.label, updatePackage.label) &&
        Objects.equals(this.description, updatePackage.description) &&
        Objects.equals(this.changeLog, updatePackage.changeLog) &&
        Objects.equals(this.license, updatePackage.license) &&
        Objects.equals(this.binaryURL, updatePackage.binaryURL) &&
        Objects.equals(this.binaryChecksum, updatePackage.binaryChecksum) &&
        Objects.equals(this.binarySignature, updatePackage.binarySignature) &&
        Objects.equals(this.binaryHashType, updatePackage.binaryHashType) &&
        Objects.equals(this.binarySize, updatePackage.binarySize) &&
        Objects.equals(this.binaryOS, updatePackage.binaryOS) &&
        Objects.equals(this.binaryArch, updatePackage.binaryArch) &&
        Objects.equals(this.isPatch, updatePackage.isPatch) &&
        Objects.equals(this.patchAlgorithm, updatePackage.patchAlgorithm) &&
        Objects.equals(this.serviceName, updatePackage.serviceName) &&
        Objects.equals(this.status, updatePackage.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(packageName, version, releaseDate, label, description, changeLog, license, binaryURL, binaryChecksum, binarySignature, binaryHashType, binarySize, binaryOS, binaryArch, isPatch, patchAlgorithm, serviceName, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePackage {\n");
    
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    changeLog: ").append(toIndentedString(changeLog)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    binaryURL: ").append(toIndentedString(binaryURL)).append("\n");
    sb.append("    binaryChecksum: ").append(toIndentedString(binaryChecksum)).append("\n");
    sb.append("    binarySignature: ").append(toIndentedString(binarySignature)).append("\n");
    sb.append("    binaryHashType: ").append(toIndentedString(binaryHashType)).append("\n");
    sb.append("    binarySize: ").append(toIndentedString(binarySize)).append("\n");
    sb.append("    binaryOS: ").append(toIndentedString(binaryOS)).append("\n");
    sb.append("    binaryArch: ").append(toIndentedString(binaryArch)).append("\n");
    sb.append("    isPatch: ").append(toIndentedString(isPatch)).append("\n");
    sb.append("    patchAlgorithm: ").append(toIndentedString(patchAlgorithm)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

