/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AuthLdapMapping
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T15:42:51.155Z")
public class AuthLdapMapping {
  @SerializedName("LeftAttribute")
  private String leftAttribute = null;

  @SerializedName("RightAttribute")
  private String rightAttribute = null;

  @SerializedName("RuleString")
  private String ruleString = null;

  @SerializedName("RolePrefix")
  private String rolePrefix = null;

  public AuthLdapMapping leftAttribute(String leftAttribute) {
    this.leftAttribute = leftAttribute;
    return this;
  }

   /**
   * Get leftAttribute
   * @return leftAttribute
  **/
  @ApiModelProperty(value = "")
  public String getLeftAttribute() {
    return leftAttribute;
  }

  public void setLeftAttribute(String leftAttribute) {
    this.leftAttribute = leftAttribute;
  }

  public AuthLdapMapping rightAttribute(String rightAttribute) {
    this.rightAttribute = rightAttribute;
    return this;
  }

   /**
   * Get rightAttribute
   * @return rightAttribute
  **/
  @ApiModelProperty(value = "")
  public String getRightAttribute() {
    return rightAttribute;
  }

  public void setRightAttribute(String rightAttribute) {
    this.rightAttribute = rightAttribute;
  }

  public AuthLdapMapping ruleString(String ruleString) {
    this.ruleString = ruleString;
    return this;
  }

   /**
   * Get ruleString
   * @return ruleString
  **/
  @ApiModelProperty(value = "")
  public String getRuleString() {
    return ruleString;
  }

  public void setRuleString(String ruleString) {
    this.ruleString = ruleString;
  }

  public AuthLdapMapping rolePrefix(String rolePrefix) {
    this.rolePrefix = rolePrefix;
    return this;
  }

   /**
   * Get rolePrefix
   * @return rolePrefix
  **/
  @ApiModelProperty(value = "")
  public String getRolePrefix() {
    return rolePrefix;
  }

  public void setRolePrefix(String rolePrefix) {
    this.rolePrefix = rolePrefix;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AuthLdapMapping authLdapMapping = (AuthLdapMapping) o;
    return Objects.equals(this.leftAttribute, authLdapMapping.leftAttribute) &&
        Objects.equals(this.rightAttribute, authLdapMapping.rightAttribute) &&
        Objects.equals(this.ruleString, authLdapMapping.ruleString) &&
        Objects.equals(this.rolePrefix, authLdapMapping.rolePrefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(leftAttribute, rightAttribute, ruleString, rolePrefix);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AuthLdapMapping {\n");
    
    sb.append("    leftAttribute: ").append(toIndentedString(leftAttribute)).append("\n");
    sb.append("    rightAttribute: ").append(toIndentedString(rightAttribute)).append("\n");
    sb.append("    ruleString: ").append(toIndentedString(ruleString)).append("\n");
    sb.append("    rolePrefix: ").append(toIndentedString(rolePrefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

