/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CertLicenseInfo;
import java.io.IOException;

/**
 * CertLicenseStatsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T15:42:51.155Z")
public class CertLicenseStatsResponse {
  @SerializedName("License")
  private CertLicenseInfo license = null;

  @SerializedName("ActiveUsers")
  private String activeUsers = null;

  @SerializedName("ActivePeers")
  private String activePeers = null;

  public CertLicenseStatsResponse license(CertLicenseInfo license) {
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @ApiModelProperty(value = "")
  public CertLicenseInfo getLicense() {
    return license;
  }

  public void setLicense(CertLicenseInfo license) {
    this.license = license;
  }

  public CertLicenseStatsResponse activeUsers(String activeUsers) {
    this.activeUsers = activeUsers;
    return this;
  }

   /**
   * Get activeUsers
   * @return activeUsers
  **/
  @ApiModelProperty(value = "")
  public String getActiveUsers() {
    return activeUsers;
  }

  public void setActiveUsers(String activeUsers) {
    this.activeUsers = activeUsers;
  }

  public CertLicenseStatsResponse activePeers(String activePeers) {
    this.activePeers = activePeers;
    return this;
  }

   /**
   * Get activePeers
   * @return activePeers
  **/
  @ApiModelProperty(value = "")
  public String getActivePeers() {
    return activePeers;
  }

  public void setActivePeers(String activePeers) {
    this.activePeers = activePeers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CertLicenseStatsResponse certLicenseStatsResponse = (CertLicenseStatsResponse) o;
    return Objects.equals(this.license, certLicenseStatsResponse.license) &&
        Objects.equals(this.activeUsers, certLicenseStatsResponse.activeUsers) &&
        Objects.equals(this.activePeers, certLicenseStatsResponse.activePeers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(license, activeUsers, activePeers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CertLicenseStatsResponse {\n");
    
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    activeUsers: ").append(toIndentedString(activeUsers)).append("\n");
    sb.append("    activePeers: ").append(toIndentedString(activePeers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

