/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ctlServiceCommand
 */
@JsonAdapter(CtlServiceCommand.Adapter.class)
public enum CtlServiceCommand {
  
  START("START"),
  
  STOP("STOP");

  private String value;

  CtlServiceCommand(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static CtlServiceCommand fromValue(String text) {
    for (CtlServiceCommand b : CtlServiceCommand.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<CtlServiceCommand> {
    @Override
    public void write(final JsonWriter jsonWriter, final CtlServiceCommand enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public CtlServiceCommand read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return CtlServiceCommand.fromValue(String.valueOf(value));
    }
  }
}

