/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DocstoreDocumentQuery;
import java.io.IOException;

/**
 * DocstoreDeleteDocumentsRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T15:42:51.155Z")
public class DocstoreDeleteDocumentsRequest {
  @SerializedName("StoreID")
  private String storeID = null;

  @SerializedName("DocumentID")
  private String documentID = null;

  @SerializedName("Query")
  private DocstoreDocumentQuery query = null;

  public DocstoreDeleteDocumentsRequest storeID(String storeID) {
    this.storeID = storeID;
    return this;
  }

   /**
   * Get storeID
   * @return storeID
  **/
  @ApiModelProperty(value = "")
  public String getStoreID() {
    return storeID;
  }

  public void setStoreID(String storeID) {
    this.storeID = storeID;
  }

  public DocstoreDeleteDocumentsRequest documentID(String documentID) {
    this.documentID = documentID;
    return this;
  }

   /**
   * Get documentID
   * @return documentID
  **/
  @ApiModelProperty(value = "")
  public String getDocumentID() {
    return documentID;
  }

  public void setDocumentID(String documentID) {
    this.documentID = documentID;
  }

  public DocstoreDeleteDocumentsRequest query(DocstoreDocumentQuery query) {
    this.query = query;
    return this;
  }

   /**
   * Get query
   * @return query
  **/
  @ApiModelProperty(value = "")
  public DocstoreDocumentQuery getQuery() {
    return query;
  }

  public void setQuery(DocstoreDocumentQuery query) {
    this.query = query;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocstoreDeleteDocumentsRequest docstoreDeleteDocumentsRequest = (DocstoreDeleteDocumentsRequest) o;
    return Objects.equals(this.storeID, docstoreDeleteDocumentsRequest.storeID) &&
        Objects.equals(this.documentID, docstoreDeleteDocumentsRequest.documentID) &&
        Objects.equals(this.query, docstoreDeleteDocumentsRequest.query);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storeID, documentID, query);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocstoreDeleteDocumentsRequest {\n");
    
    sb.append("    storeID: ").append(toIndentedString(storeID)).append("\n");
    sb.append("    documentID: ").append(toIndentedString(documentID)).append("\n");
    sb.append("    query: ").append(toIndentedString(query)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

