/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.IdmWorkspace;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RestWorkspaceCollection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-09-25T16:31:30.189Z")
public class RestWorkspaceCollection {
  @SerializedName("Workspaces")
  private List<IdmWorkspace> workspaces = null;

  @SerializedName("Total")
  private Integer total = null;

  public RestWorkspaceCollection workspaces(List<IdmWorkspace> workspaces) {
    this.workspaces = workspaces;
    return this;
  }

  public RestWorkspaceCollection addWorkspacesItem(IdmWorkspace workspacesItem) {
    if (this.workspaces == null) {
      this.workspaces = new ArrayList<IdmWorkspace>();
    }
    this.workspaces.add(workspacesItem);
    return this;
  }

   /**
   * Get workspaces
   * @return workspaces
  **/
  @ApiModelProperty(value = "")
  public List<IdmWorkspace> getWorkspaces() {
    return workspaces;
  }

  public void setWorkspaces(List<IdmWorkspace> workspaces) {
    this.workspaces = workspaces;
  }

  public RestWorkspaceCollection total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @ApiModelProperty(value = "")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestWorkspaceCollection restWorkspaceCollection = (RestWorkspaceCollection) o;
    return Objects.equals(this.workspaces, restWorkspaceCollection.workspaces) &&
        Objects.equals(this.total, restWorkspaceCollection.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workspaces, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestWorkspaceCollection {\n");
    
    sb.append("    workspaces: ").append(toIndentedString(workspaces)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

