/*
 * Pydio Cells Rest API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.TreeNode;
import java.io.IOException;

/**
 * TreeReadNodeRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-04-25T15:42:51.155Z")
public class TreeReadNodeRequest {
  @SerializedName("Node")
  private TreeNode node = null;

  @SerializedName("WithCommits")
  private Boolean withCommits = null;

  public TreeReadNodeRequest node(TreeNode node) {
    this.node = node;
    return this;
  }

   /**
   * Get node
   * @return node
  **/
  @ApiModelProperty(value = "")
  public TreeNode getNode() {
    return node;
  }

  public void setNode(TreeNode node) {
    this.node = node;
  }

  public TreeReadNodeRequest withCommits(Boolean withCommits) {
    this.withCommits = withCommits;
    return this;
  }

   /**
   * Get withCommits
   * @return withCommits
  **/
  @ApiModelProperty(value = "")
  public Boolean isWithCommits() {
    return withCommits;
  }

  public void setWithCommits(Boolean withCommits) {
    this.withCommits = withCommits;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreeReadNodeRequest treeReadNodeRequest = (TreeReadNodeRequest) o;
    return Objects.equals(this.node, treeReadNodeRequest.node) &&
        Objects.equals(this.withCommits, treeReadNodeRequest.withCommits);
  }

  @Override
  public int hashCode() {
    return Objects.hash(node, withCommits);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreeReadNodeRequest {\n");
    
    sb.append("    node: ").append(toIndentedString(node)).append("\n");
    sb.append("    withCommits: ").append(toIndentedString(withCommits)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

